
#fill format {0}xxxx{1}ewefv3{2}
def formatfill(raw = "",lis = []):
    bit = raw.count("{")
    temp = raw
    for xx in range(bit):
        temp = temp.replace("{"+str(xx)+"}",str(lis[xx]))
    return temp


if __name__ == "__main__":
    from clicklist import defclock
    test = "{0}.{1}.a.com"
    cl = defclock(test.count("{"),10)
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))
    print(formatfill(test,cl.tick()))